# Generated by Django 4.2.30 on 2026-08-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name_fa', models.CharField(default='فروشگاه من', max_length=150, verbose_name='Store name (Persian)')),
                ('store_name_en', models.CharField(default='My Store', max_length=150, verbose_name='Store name (English)')),
                ('slogan_fa', models.CharField(blank=True, max_length=250, verbose_name='Slogan (Persian)')),
                ('slogan_en', models.CharField(blank=True, max_length=250, verbose_name='Slogan (English)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/', verbose_name='Logo')),
                ('store_url', models.URLField(default='https://example.com', help_text='Public URL of the store - this is what the QR code will point to.', verbose_name='Store URL')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone number')),
                ('address_fa', models.CharField(blank=True, max_length=300, verbose_name='Address (Persian)')),
                ('address_en', models.CharField(blank=True, max_length=300, verbose_name='Address (English)')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram URL')),
                ('whatsapp', models.URLField(blank=True, verbose_name='WhatsApp URL')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='store/qr/', verbose_name='QR code (auto-generated)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store settings',
                'verbose_name_plural': 'Store settings',
            },
        ),
    ]
