# Generated by Django 4.2.30 on 2026-08-05 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=150, verbose_name='Name (Persian)')),
                ('name_en', models.CharField(max_length=150, verbose_name='Name (English)')),
                ('slug', models.SlugField(allow_unicode=True, max_length=170, unique=True, verbose_name='Slug')),
                ('description_fa', models.TextField(blank=True, verbose_name='Description (Persian)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category', verbose_name='Parent category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=200, verbose_name='Name (Persian)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='Slug')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU / product code')),
                ('short_description_fa', models.CharField(blank=True, max_length=300, verbose_name='Short description (Persian)')),
                ('short_description_en', models.CharField(blank=True, max_length=300, verbose_name='Short description (English)')),
                ('description_fa', models.TextField(blank=True, verbose_name='Full description (Persian)')),
                ('description_en', models.TextField(blank=True, verbose_name='Full description (English)')),
                ('price', models.DecimalField(decimal_places=0, help_text='Price in Toman', max_digits=12, verbose_name='Price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=0, help_text='Leave empty if the product has no discount.', max_digits=12, null=True, verbose_name='Discount price')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active / visible on site')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=100, verbose_name='Title (Persian)')),
                ('title_en', models.CharField(max_length=100, verbose_name='Title (English)')),
                ('value_fa', models.CharField(max_length=250, verbose_name='Value (Persian)')),
                ('value_en', models.CharField(max_length=250, verbose_name='Value (English)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product')),
            ],
            options={
                'verbose_name': 'Specification',
                'verbose_name_plural': 'Specifications',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt text')),
                ('is_main', models.BooleanField(default=False, verbose_name='Main image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Product image',
                'verbose_name_plural': 'Product images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
